//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string But1 {
            get {
                return ResourceManager.GetString("But1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string But1f2 {
            get {
                return ResourceManager.GetString("But1f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOSTRAR INFO.
        /// </summary>
        public static string But1uc {
            get {
                return ResourceManager.GetString("But1uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR.
        /// </summary>
        public static string But2uc {
            get {
                return ResourceManager.GetString("But2uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string But3 {
            get {
                return ResourceManager.GetString("But3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string cb1f2 {
            get {
                return ResourceManager.GetString("cb1f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponible.
        /// </summary>
        public static string cb1uc {
            get {
                return ResourceManager.GetString("cb1uc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACEPTAR.
        /// </summary>
        public static string dllbut {
            get {
                return ResourceManager.GetString("dllbut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SUMAR NUMEROS.
        /// </summary>
        public static string dlllabel {
            get {
                return ResourceManager.GetString("dlllabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL.
        /// </summary>
        public static string dllresul {
            get {
                return ResourceManager.GetString("dllresul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE DEL POKEMON.
        /// </summary>
        public static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EDITAR INFORMACION.
        /// </summary>
        public static string label1f2 {
            get {
                return ResourceManager.GetString("label1f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIPO DEL POKEMON.
        /// </summary>
        public static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE DEL POKEMON.
        /// </summary>
        public static string label2f2 {
            get {
                return ResourceManager.GetString("label2f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NÚMERO DE POKEDEX.
        /// </summary>
        public static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIPO DEL POKEMON.
        /// </summary>
        public static string label3f2 {
            get {
                return ResourceManager.GetString("label3f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CÓDIGO DE POKEMON.
        /// </summary>
        public static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NÚMERO DE POKEDEX.
        /// </summary>
        public static string label4f2 {
            get {
                return ResourceManager.GetString("label4f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRENADOR.
        /// </summary>
        public static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CÓDIGO DE POKEMON.
        /// </summary>
        public static string label5f2 {
            get {
                return ResourceManager.GetString("label5f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGISTRO DE VIDEOJUEGOS.
        /// </summary>
        public static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRENADOR.
        /// </summary>
        public static string label6f2 {
            get {
                return ResourceManager.GetString("label6f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAMBIAR IDIOMA.
        /// </summary>
        public static string label9 {
            get {
                return ResourceManager.GetString("label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GRAFICO.
        /// </summary>
        public static string labelgra {
            get {
                return ResourceManager.GetString("labelgra", resourceCulture);
            }
        }
    }
}
